apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy3
  labels:
    app: app-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-v1
  template:
    metadata: 
      labels:
        app: app-v1
    spec:
      containers:
      - name: sample-ctr
        image: devopstrainer/deploy:v1
        ports:
        - containerPort: 80
        env:
        - name: CONF_USER
          valueFrom:
            configMapKeyRef:
              name: user-cred
              key: user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: user-pwd
              key: password